<a href="https://colab.research.google.com/github/Ilya-2/Ad-hoc/blob/main/ad_hoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ad-hoc запросы

In [ ]:
df = pd.read_csv('/content/products_data.csv')
df1 = pd.read_csv('/content/sales_data.csv')

Вопрос №1
В каком регионе было продано наибольшее количество продуктов категории "Смартфоны"?

In [ ]:
df.head()

   product_id                 product_name    category manufacturer
0         101       Ноутбук HP Pavilion 15    Ноутбуки            A
1         102  Смартфон Samsung Galaxy S21   Смартфоны            B
2         103       Планшет Apple iPad Air    Планшеты            C
3         104     Наушники Sony WH-1000XM4    Наушники            D
4         105         Телевизор LG OLED CX  Телевизоры            E

In [ ]:
df1.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север

In [ ]:
itog_df = df.merge(df1, left_on='product_id', right_on='product_id')

itog_df = itog_df[itog_df['category'] == 'Смартфоны'].groupby('region')['quantity'].agg('sum').rename('Кол-во продано')

itog_df.sort_values(ascending=False)

region
Восток    4
Юг        3
Запад     2
Север     1
Name: Кол-во продано, dtype: int64

Вопрос №2
Какова разница между максимальной и минимальной средней ценой продуктов категории "Ноутбуки" между всеми производителями? Ответ округлите до целых.

In [ ]:
df = pd.read_csv('/content/products_data.csv')
df1 = pd.read_csv('/content/sales_data.csv')

itog_df = df.merge(df1, left_on='product_id', right_on='product_id')

df_laptop = itog_df.query('category == "Ноутбуки"')

manufacturer_avg_price = df_laptop.groupby('manufacturer')['price_per_unit'].mean()

round(max(manufacturer_avg_price) - min(manufacturer_avg_price))

200

Вопрос №3
Какой покупатель совершил заказы на наибольшую сумму за все время?

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

one_major_user = df_sales.groupby('customer_id')['total_price'].agg('sum').rename('Общая сумма')

one_major_user.sort_values(ascending=False).head(1)

customer_id
1003    3550
Name: Общая сумма, dtype: int64

Вопрос №4
Какова доля продаж продуктов категории "Планшеты" от общей выручки за все время (учитывая только продукты, информация о которых есть в products_data)? Ответ округлите до 2 знака после запятой. Разделитель разряда - точка.

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id', how='left')

res = join_df[join_df['category'] == 'Планшеты']['total_price'].sum().tolist()

revenue_laptop = (res / join_df['total_price'].sum()).round(2)

revenue_laptop

np.float64(0.25)

Вопрос №5
Какова абсолютная разница в средней цене за единицу продуктов категории "Смартфоны" между двумя регионами с наибольшей общей выручкой по всем категориям товаров (учитывая только продукты, информация о которых есть в products_data)? Ответ округлите до целых и возьмите по модулю.

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

In [ ]:
df_product.head()

   product_id                 product_name    category manufacturer
0         101       Ноутбук HP Pavilion 15    Ноутбуки            A
1         102  Смартфон Samsung Galaxy S21   Смартфоны            B
2         103       Планшет Apple iPad Air    Планшеты            C
3         104     Наушники Sony WH-1000XM4    Наушники            D
4         105         Телевизор LG OLED CX  Телевизоры            E

In [ ]:
df_sales.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север

In [ ]:
join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id', how='left')

two_major_revenue = join_df.groupby('region')['total_price'].agg('sum').rename('Общая выручка').reset_index()

two_major_revenue = two_major_revenue.sort_values('Общая выручка', ascending=False).head(2)

df_smartphone = join_df.query('category == "Смартфоны"')

avg_price_two_regions = two_major_revenue.merge(df_smartphone, on='region').groupby('region')['price_per_unit'].agg('mean')

int(abs(avg_price_two_regions.iloc[0] - avg_price_two_regions.iloc[1]))

275

Вопрос №6
Сколько в среднем уникальных категорий продуктов было продано по всем регионам?

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

df_distinct_category = join_df.groupby('region')['category'].agg('nunique')

df_distinct_category.mean()

np.float64(5.0)

Вопрос №7
Какой производитель представлен в наибольшем количестве различных категорий продуктов?

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

df_manufacturer_diversity = join_df.groupby('manufacturer')['category'].agg('nunique')

df_manufacturer_diversity.sort_values(ascending=False).head(1)

manufacturer
E    4
Name: category, dtype: int64

Вопрос №8
В каком месяце было продано больше всего продуктов категории "Планшеты" в регионе "Север"? (ответ представьте в виде номера месяца)

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

join_df['order_date'] = pd.to_datetime(join_df['order_date']).dt.month

month_more_sold = join_df.query('category == "Планшеты" and region == "Север"').groupby('order_date')['quantity'].agg('sum')

month_more_sold

order_date
8    1
Name: quantity, dtype: int64

Вопрос №9
Какой производитель продал продукты на наибольшую сумму в регионе "Юг" за март 2023 года?

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

join_df['order_date'] = pd.to_datetime(join_df['order_date'])

manufacturer_largest_price = join_df[(join_df['region'] == 'Юг') & ((join_df['order_date'] >= '2023-03-01') & (join_df['order_date'] <= '2023-03-31'))]

manufacturer_largest_price.groupby('manufacturer')['total_price'].agg('sum').sort_values(ascending=False)

manufacturer
B    700
Name: total_price, dtype: int64

Вопрос №10
Сколько покупателей совершили заказы на продукты хотя бы трех разных категорий?

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

df_customer_diversity = join_df.groupby('customer_id')['category'].agg('nunique')
res = df_customer_diversity[df_customer_diversity >= 3]

len(res)

1

Вопрос №11
Какова доля продаж продуктов производителя "C" от общей выручки за все время в регионе "Север"? Ответ округлите до 2 знака после запятой. В качестве разделителя разрядов используйте точку.

In [ ]:
df_product = pd.read_csv('/content/products_data.csv')
df_sales = pd.read_csv('/content/sales_data.csv')

In [ ]:
df_product.head()

   product_id                 product_name    category manufacturer
0         101       Ноутбук HP Pavilion 15    Ноутбуки            A
1         102  Смартфон Samsung Galaxy S21   Смартфоны            B
2         103       Планшет Apple iPad Air    Планшеты            C
3         104     Наушники Sony WH-1000XM4    Наушники            D
4         105         Телевизор LG OLED CX  Телевизоры            E

In [ ]:
df_sales.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север

In [ ]:
join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

region_server = join_df[join_df['region'] == 'Север'].groupby('manufacturer')['total_price'].agg('sum')

region_server = (region_server / sum(region_server)).round(2)

region_server

manufacturer
A    0.30
B    0.10
C    0.27
D    0.08
E    0.25
Name: total_price, dtype: float64

Вопрос №12
Найдите покупателей, которые купили более чем 15% уникальных связок "Категория - Производитель". Если таких покупателей несколько - напишите их через запятую с пробелом в порядке возрастания результата.

In [ ]:
import pandas as pd

df_product = pd.read_csv('products_data.csv')
df_sales = pd.read_csv('sales_data.csv')

In [ ]:
df_product.head()

   product_id                 product_name    category manufacturer
0         101       Ноутбук HP Pavilion 15    Ноутбуки            A
1         102  Смартфон Samsung Galaxy S21   Смартфоны            B
2         103       Планшет Apple iPad Air    Планшеты            C
3         104     Наушники Sony WH-1000XM4    Наушники            D
4         105         Телевизор LG OLED CX  Телевизоры            E

In [ ]:
df_sales.head()

,order_id,product_id,customer_id,order_date,quantity,price_per_unit,total_price,payment_method,region
0,1,101,1001,2022-02-15,2,500,1000,Карта,Север
1,2,102,1002,2022-03-20,1,800,800,Наличные,Юг
2,3,103,1003,2022-03-25,3,300,900,Карта,Запад
3,4,104,1001,2022-04-10,2,400,800,Карта,Восток
4,5,105,1004,2022-04-15,1,700,700,Наличные,Север

In [ ]:
#df1 = join_df.groupby(['manufacturer', 'category'])['customer_id'].agg('count')
#df_count_combo = len(df1)

15

In [ ]:
join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

join_df = join_df[['customer_id', 'category', 'manufacturer']].drop_duplicates()

df_count_combo_customer = join_df.groupby('customer_id')['manufacturer'].agg('count')

#df_count_combo_customer = join_df.groupby('customer_id').size()

df_count_combo = len(join_df[['category', 'manufacturer']].drop_duplicates())

df_15_percentage_customer = (df_count_combo_customer / df_count_combo) * 100

df_15_percentage_customer[df_15_percentage_customer > 15]

customer_id
1001    20.0
1003    20.0
Name: manufacturer, dtype: float64

Вопрос №13
Какое максимальное количество продуктов было продано в один заказ?

In [ ]:
df_product = pd.read_csv('products_data.csv')
df_sales = pd.read_csv('sales_data.csv')

max_quantity_product = df_sales.groupby('order_id')['quantity'].agg('sum')
max_quantity_product.max()

4

Вопрос №14
Какой производитель имеет самую высокую среднюю цену продукта среди всех категорий?

In [ ]:
df_product = pd.read_csv('products_data.csv')
df_sales = pd.read_csv('sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

max_price_manufacturer = join_df.groupby('manufacturer')['price_per_unit'].mean()
max_price_manufacturer.sort_values(ascending=False).head(1)

manufacturer
E    683.333333
Name: price_per_unit, dtype: float64

Вопрос №15
Каково общее количество уникальных производителей, чьи продукты были куплены менее чем в 3 регионах?

In [ ]:
df_product = pd.read_csv('products_data.csv')
df_sales = pd.read_csv('sales_data.csv')

join_df = df_product.merge(df_sales, left_on='product_id', right_on='product_id')

min_region = join_df.groupby('manufacturer')['region'].agg('nunique')
min_region = min_region[min_region < 3]
len(min_region)

0